name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'

jobs:
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout sources
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "./"
          target: "/tmp/runner/"
  build_and_push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: copy_files
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: build new docker container
        uses: appleboy/ssh-action@master
        env: 
          DOCKERUSER: ${{ secrets.DOCKERUSER }}
          DOCKERTOKEN: ${{ secrets.DOCKERTOKEN }}
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          envs: DOCKERUSER,DOCKERTOKEN
          script: |
            cd /tmp/runner/ &&
            docker login -u $DOCKERUSER -p $DOCKERTOKEN && 
            docker image build . -t weisserdev/github-action-runner:latest &&
            docker image push weisserdev/github-action-runner:latest 