name: create_new_runner

on:
  workflow_dispatch:


env:
  IMAGE_NAME: image

jobs:
  # This workflow contains a single job called "build"
  copy_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: checkout sources
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "./"
          target: "/tmp/runner"
  runner:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: copy_files
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: starts a mongodb with network and mounted data directory
        uses: appleboy/ssh-action@master
        env: 
          GITHUB_REPO_TOKEN: ${{ secrets.REPO_RUNNER_TOKEN }}
          GITHUB_REPO_URL: ${{ github.repository }}
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSH_KEY }}
          envs: GITHUB_REPO_TOKEN,GITHUB_REPO_URL
          script: |
            cd /tmp/runner/ &&
            docker build -t runner --build-arg GITHUB_REPO_TOKEN=$GITHUB_REPO_TOKEN --build-arg GITHUB_REPO_URL=$GITHUB_REPO_URL . &&
            docker run -d runner